vendor: KBSYS Inc.
name: Bizmicro-Portal
version: 0.9                                
website_url: http://portal.kb-sys.co.kr
type: hosted platform
description: Bizmicro is a practical, use-oriented call support platform for customer consultations.